version: '3.8'
services:
  web:
    build: .
    container_name: php_cms_web
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
    environment:
      DB_HOST: "${DB_HOST}"             
      DB_USER: "${DB_USER}"
      DB_PASS: "${DB_PASS}"
      DB_NAME: "${DB_NAME}"
      DB_PORT: "${DB_PORT}"
    networks:
      - internal

networks:
  internal:
    external: true
